### ISSUE TITLE
Support copying files w/o templating

### ISSUE THREAD

**Issue by omallo** [microconfig/microconfig#42]
Microconfig supports copying arbitrary template files by using "mc.template" or "mc.mustache" which is a great functionality for templating files and moving them to the build folder.

In some cases, one might want to copy binary files (e.g. a Java keystore) w/o any templating functionality. In such cases, I do not want to use "mc.template" or "mc.mustache" since this might corrupt the binary file. However, I would still like Microconfig to copy the file for me, even if no templating is applied, in order to have all the files required by my service in the Microconfig build folder.

Would it make sense to introduce a way to copy files w/o applying any templating, e.g. by having "mc.file.*.[fromFile|toFile]" variables similar to the existing ones which just copy the file?

**Comment by alxmatorin** [comment]
Good feature! Will be implemented soon. 
The syntax will be mc.file.* 
Thank you!

**Comment by omallo** [comment]
Great to hear! And thanks for the quick feedback :)

**Comment by alxmatorin** [comment]
implemented v.4.4.0 and released to maven central and home brew.
Could you please check it out?
The plugin will be updated a little bit later.

**Comment by omallo** [comment]
I just tested it with the microconfig binary v.4.4.0 which I installed using brew on MacOS and so far it works as expected.

Thanks a lot for the really quick implementation!

You can close the issue if you want.
