### ISSUE TITLE
YAML multiline values do not work

### ISSUE THREAD

**Issue by tomaszpierscinski-s8** [microconfig/microconfig#54]
Hi,

I need to use multiline strings in YAML, but `>` and `|` seems not working. For example:
```
testmultiline: >
  line 1
  line 2
```

```
$ java -jar microconfig.jar -e test
Filtered 15 component(s) in [test] env.
Using settings from /project/microconfig.yaml
java.lang.IllegalArgumentException: Incorrect delimiter in '  line 1' in '../components/apps/base-java-app/application.yml:16'
Yaml property must contain ':' as delimiter.
```

Would it be possible to implement this? :) Thanks.

**Comment by kapodes** [comment]
Thank you for highlighting this. We will add it to microconfig :)

Btw you did you know that we have binary builds for microconfig? 
You can pick one for your OS in our releases, so you don't have to do `java -jar microconfig.jar` anymore :)

**Comment by tomaszpierscinski-s8** [comment]
> Thank you for highlighting this. We will add it to microconfig :)
> 
> Btw you did you know that we have binary builds for microconfig? You can pick one for your OS in our releases, so you don't have to do `java -jar microconfig.jar` anymore :)

Yes I know, that was just from testing. ;) Btw. when do you think this fix may be ready?

**Comment by kapodes** [comment]
```
Btw. when do you think this fix may be ready?
```
Let's aim at next week

**Comment by kapodes** [comment]
@tomaszpierscinski-s8 we added support for multiline in 4.9.0. 
please use `key: |` syntax.

**Comment by tomaszpierscinski-s8** [comment]
Works perfectly. Thank you. What about `>` syntax? It is also useful sometimes.

**Comment by kapodes** [comment]
No plans for it yet. `>` is too complex comparing to `|`
