### ISSUE TITLE
How to use include placeholder in .properties or toml format file

### ISSUE THREAD

**Issue by g0tbread** [microconfig/microconfig#61]
Hello
If the application configuration file is in .properties or .toml format, does microconfig support the use of include placeholders?
Thanks

**Comment by alxmatorin** [comment]
Hello @g0tbread.

You can include key/value from the same config types.
There are several standard config types ([https://microconfig.io/documentation.html#/?id=service-configuration-types](https://microconfig.io/documentation.html#/?id=service-configuration-types))

So you can include *.properties from/to *.yaml and *.properties files.

*.toml is a standard config type. But you can describe your own config type in microconfig.yaml (must be in the config root).
microconfig.yaml example is here: https://github.com/microconfig/microconfig/blob/master/microconfig-core/src/test/resources/configTypes/microconfig.yaml
